const KEY="goal-assistant-v6";
const initial={goals:[],activities:[],media:[],rewards:[],tokens:[],settings:{}};
let S=load(),route="today";
const $=s=>document.querySelector(s), esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const id=()=>crypto.randomUUID?.()||Date.now()+"-"+Math.random();
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(S));render()}
function day(){return new Date().toISOString().slice(0,10)}
function labelType(t){return ({book:"Buch",movie:"Film",series:"Serie",game:"Game",trip:"Ausflug",restaurant:"Restaurant"}[t]||t)}
function icon(t){return ({book:"📚",movie:"🎬",series:"📺",game:"🎮",trip:"🏔️",restaurant:"🍽️"}[t]||"✨")}
function balance(){return S.tokens.reduce((a,x)=>a+x.amount,0)}
function period(d,t){let x=new Date(d+"T12:00:00"),y=x.getFullYear(),m=x.getMonth()+1;if(t==="day")return d;if(t==="week"){x.setDate(x.getDate()-((x.getDay()+6)%7));return x.toISOString().slice(0,10)}if(t==="month")return y+"-"+String(m).padStart(2,"0");if(t==="quarter")return y+"-Q"+(Math.floor(x.getMonth()/3)+1);return y}
function calc(g,date=day()){let a=S.activities.filter(x=>x.goalId===g.id), regular=a.filter(x=>x.kind==="regular"), pk=period(date,g.tracking), cur=regular.filter(x=>period(x.date,g.tracking)===pk).reduce((s,x)=>s+(Number(x.value)||1),0);let pct=g.target?cur/g.target*100:null;return{a,cur,pct,extra:a.filter(x=>x.kind==="extra").length,exc:a.filter(x=>x.kind==="exception").length,miss:a.filter(x=>x.kind==="missed").length}}
function render(){const titles={today:"Heute",goals:"Ziele",library:"Sammlung",stats:"Statistik",rewards:"Belohnungen"};$("#title").textContent=titles[route];document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.route===route));$("#main").innerHTML=({today:todayView,goals:goalsView,library:libraryView,stats:statsView,rewards:rewardsView}[route])();wire()}
function todayView(){let gs=S.goals.filter(g=>g.status!=="archived");return `<section class="hero"><div class="muted" style="color:#94a3b8">${new Intl.DateTimeFormat("de-DE",{dateStyle:"full"}).format(new Date())}</div><h2>Dein Tag.</h2><p>${gs.length?"Kleine Schritte, große Jahresauswertung.":"Lege dein erstes Ziel an."}</p><div class="big" style="margin-top:13px">🪙 ${balance()} Tokens</div></section><div class="grid"><div class="metric"><div class="v">${S.activities.filter(a=>a.date===day()&&a.kind==="regular").length}</div><div class="l">Heute erledigt</div></div><div class="metric"><div class="v">${S.media.filter(m=>m.completedDate===day()).length}</div><div class="l">Heute abgeschlossen</div></div></div><div class="section"><h2>🎯 Aktive Ziele</h2><button class="btn primary" data-a="goal-add">＋ Ziel</button></div>${gs.map(goalCard).join("")||`<div class="empty">Noch keine Ziele vorhanden.</div>`}`}
function goalCard(g){let c=calc(g),pct=c.pct==null?null:Math.round(c.pct),p=Math.min(100,Math.max(0,c.pct||0));return `<article class="card"><div class="head"><div><h3>${esc(g.icon)} ${esc(g.name)}</h3><div class="muted">${esc(g.trackingLabel)}${g.target!=null?" · "+esc(g.direction==="max"?"max.":"mind.")+" "+g.target+" "+esc(g.unit):""}</div></div><span class="pill ${g.direction==="max"?(c.cur<=g.target?"good":"bad"):(pct>=100?"good":"")}">${pct==null?"ohne %":pct+"%"}</span></div>${g.target!=null?`<div class="bar ${pct>100?"over":""}"><i style="width:${p}%"></i></div><div class="stat"><span>${c.cur} / ${g.target} ${esc(g.unit)}</span><span>⭐ ${c.extra} · 🤒 ${c.exc}</span></div>`:""}<div class="actions"><button class="btn primary" data-a="activity" data-id="${g.id}">＋ Aktivität</button><button class="btn" data-a="timer" data-id="${g.id}">⏱️ Timer</button><button class="btn" data-a="goal-edit" data-id="${g.id}">✏️</button></div></article>`}
function goalsView(){return `<div class="section"><h2>🎯 Deine Ziele</h2><button class="btn primary" data-a="goal-add">＋ Ziel hinzufügen</button></div>${S.goals.filter(g=>g.status!=="archived").map(goalCard).join("")||`<div class="empty">Noch keine Ziele.</div>`}`}
function libraryView(){let list=S.media.slice().sort((a,b)=>(b.completedDate||b.createdAt).localeCompare(a.completedDate||a.createdAt));return `<div class="section"><h2>📚 Meine Sammlung</h2><button class="btn primary" data-a="media-add">＋ Hinzufügen</button></div><div class="filter" id="filters"><button class="active" data-t="all">Alle</button><button data-t="book">📚 Bücher</button><button data-t="movie">🎬 Filme</button><button data-t="series">📺 Serien</button><button data-t="game">🎮 Games</button><button data-t="trip">🏔️ Ausflüge</button><button data-t="restaurant">🍽️ Restaurants</button></div><div id="mediaList">${list.map(mediaCard).join("")||`<div class="empty">Noch nichts gespeichert.</div>`}</div>`}
function mediaCard(m){return `<article class="card" data-type="${m.type}"><div class="head"><div><h3>${icon(m.type)} ${esc(m.title)}</h3><div class="muted">${labelType(m.type)} · ${esc(m.status)}${m.rating!=null?" · "+"★".repeat(Math.round(m.rating)):""}</div></div><button class="btn" data-a="media-edit" data-id="${m.id}">✏️</button></div>${m.duration?`<div class="muted" style="margin-top:8px">⏱️ ${m.duration} min</div>`:""}${m.notes?`<p class="muted">${esc(m.notes)}</p>`:""}</article>`}
function statsView(){let y=String(new Date().getFullYear()), count=t=>S.media.filter(m=>m.type===t&&m.completedDate?.startsWith(y)).length;return `<div class="section"><h2>📊 ${y} im Überblick</h2></div><div class="grid"><div class="metric"><div class="v">${count("book")}</div><div class="l">📚 Bücher</div></div><div class="metric"><div class="v">${count("movie")}</div><div class="l">🎬 Filme</div></div><div class="metric"><div class="v">${count("game")}</div><div class="l">🎮 Games</div></div><div class="metric"><div class="v">${S.activities.filter(a=>a.kind==="extra"&&a.date.startsWith(y)).length}</div><div class="l">⭐ Extra-Tage</div></div></div><div class="section"><h2>🎯 Ziel-Fortschritt</h2></div>${S.goals.filter(g=>g.status!=="archived").map(goalCard).join("")||`<div class="empty">Noch keine Ziele.</div>`}`}
function rewardsView(){return `<section class="hero"><div class="muted" style="color:#94a3b8">TOKEN-KONTO</div><h2>🪙 ${balance()} Tokens</h2><p>Deine Belohnungen sollen Motivation sein, nicht Selbstzweck.</p></section><div class="section"><h2>🎁 Belohnungen</h2><button class="btn primary" data-a="reward-add">＋ Belohnung</button></div>${S.rewards.map(r=>`<article class="card"><div class="head"><div><h3>${esc(r.icon)} ${esc(r.name)}</h3><div class="muted">${esc(r.description||"")}</div></div><span class="pill">${r.cost} 🪙</span></div><div class="actions"><button class="btn primary" data-a="redeem" data-id="${r.id}" ${balance()<r.cost?"disabled":""}>${balance()>=r.cost?"Einlösen":"Noch nicht freigeschaltet"}</button></div></article>`).join("")||`<div class="empty">Noch keine Belohnungen.</div>`}`}
function modal(html){$("#modal").innerHTML=`<div class="overlay" id="overlay"><section class="sheet">${html}</section></div>`;wire()}
function close(){ $("#modal").innerHTML=""}
function input(label,n,v="",type="text"){return `<div class="field"><label>${label}</label><input name="${n}" type="${type}" value="${esc(v)}"></div>`}
function goalForm(g){let x=g||{name:"",icon:"🎯",tracking:"none",direction:"min",target:"",unit:"",interval:""};modal(`<button class="close" data-a="close">×</button><h2>${g?"🎯 Ziel bearbeiten":"🎯 Ziel hinzufügen"}</h2><form id="gf">${input("Name *","name",x.name)}${input("Symbol","icon",x.icon)}<div class="field"><label>Tracking – optional</label><select name="tracking"><option value="none">Kein festgelegtes Tracking</option><option value="day">Täglich</option><option value="week">Wöchentlich</option><option value="month">Monatlich</option><option value="quarter">Quartalsweise</option><option value="year">Jährlich</option><option value="interval">Alle X Tage</option></select></div><div class="row">${input("Zielwert – optional","target",x.target,"number")}${input("Einheit – optional","unit",x.unit)}</div><div class="field"><label>Richtung – optional</label><select name="direction"><option value="min">Mindestens</option><option value="max">Höchstens</option></select></div><div class="field" id="intervalField" style="display:${x.tracking==="interval"?"block":"none"}">${input("Intervall in Tagen – optional","interval",x.interval??"","number")}</div><div class="actions"><button type="button" class="btn" data-a="close">Abbrechen</button><button class="btn primary">Speichern</button></div></form>`);$("#gf [name=tracking]").value=x.tracking;$("#gf [name=direction]").value=x.direction;const syncInterval=()=>{const box=$("#intervalField");if(box)box.style.display=$("#gf [name=tracking]").value==="interval"?"block":"none"};$("#gf [name=tracking]").onchange=syncInterval;syncInterval();$("#gf").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),tr=f.get("tracking"),obj={...x,id:x.id||id(),name:f.get("name").trim(),icon:f.get("icon")||"🎯",tracking:tr,trackingLabel:{none:"Ohne Tracking",day:"Täglich",week:"Wöchentlich",month:"Monatlich",quarter:"Quartalsweise",year:"Jährlich",interval:"Alle "+(f.get("interval")||"X")+" Tage"}[tr],direction:f.get("direction"),target:f.get("target")===""?null:Number(f.get("target")),unit:f.get("unit")||"",interval:tr==="interval"?(Number(f.get("interval"))||null):null,status:"active",updatedAt:new Date().toISOString()};if(!g)obj.createdAt=new Date().toISOString();S.goals=g?S.goals.map(q=>q.id===g.id?obj:q):[...S.goals,obj];save();close()}}
function activityForm(goalId){let g=S.goals.find(x=>x.id===goalId);modal(`<button class="close" data-a="close">×</button><h2>＋ Aktivität</h2><p class="muted">${esc(g.name)}</p><form id="af">${input("Datum","date",day(),"date")}<div class="field"><label>Art</label><select name="kind"><option value="regular">✅ Regulär</option><option value="extra">⭐ Extra-Tag</option><option value="exception">🤒 Ausnahme</option><option value="missed">❌ Verpasst</option></select></div>${input("Wert – optional","value",g.target||1,"number")}${input("Notiz – optional","note")}<div class="actions"><button type="button" class="btn" data-a="close">Abbrechen</button><button class="btn primary">Speichern</button></div></form>`);$("#af").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);S.activities.push({id:id(),goalId,date:f.get("date"),kind:f.get("kind"),value:Number(f.get("value"))||1,note:f.get("note")||"",createdAt:new Date().toISOString()});save();close()}}
function mediaForm(m){let x=m||{type:"book",status:"completed"};modal(`<button class="close" data-a="close">×</button><h2>📚 Sammlung</h2><form id="mf"><div class="field"><label>Typ</label><select name="type"><option value="book">📚 Buch</option><option value="movie">🎬 Film</option><option value="series">📺 Serie</option><option value="game">🎮 Game</option><option value="trip">🏔️ Ausflug</option><option value="restaurant">🍽️ Restaurant</option></select></div>${input("Titel / Name *","title",x.title)}${input("Datum abgeschlossen / besucht","date",x.completedDate||day(),"date")}<div class="row"><div class="field"><label>Status</label><select name="status"><option value="planned">Geplant</option><option value="active">Aktiv</option><option value="completed">Abgeschlossen</option><option value="paused">Pausiert</option></select></div>${input("Bewertung 0–5","rating",x.rating??"","number")}</div>${input("Autor / Entwickler / Ort – optional","creator",x.creator)}${input("Gesamtzeit in Minuten – optional","duration",x.duration||"","number")}<div class="field"><label>Notizen</label><textarea name="notes">${esc(x.notes||"")}</textarea></div><div class="actions"><button type="button" class="btn" data-a="close">Abbrechen</button><button class="btn primary">Speichern</button></div></form>`);$("#mf [name=type]").value=x.type;$("#mf [name=status]").value=x.status;$("#mf").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),obj={...x,id:x.id||id(),type:f.get("type"),title:f.get("title").trim(),completedDate:f.get("date"),status:f.get("status"),rating:f.get("rating")===""?null:Number(f.get("rating")),creator:f.get("creator")||"",duration:f.get("duration")===""?null:Number(f.get("duration")),notes:f.get("notes")||"",updatedAt:new Date().toISOString()};if(!x.id)obj.createdAt=new Date().toISOString();S.media=x.id?S.media.map(q=>q.id===x.id?obj:q):[...S.media,obj];save();close()}}
function rewardForm(){modal(`<button class="close" data-a="close">×</button><h2>🎁 Belohnung</h2><form id="rf">${input("Name *","name")}${input("Symbol","icon","🎁")}${input("Kosten in Tokens","cost",500,"number")}${input("Beschreibung","description")}<button class="btn primary">Speichern</button></form>`);$("#rf").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);S.rewards.push({id:id(),name:f.get("name").trim(),icon:f.get("icon")||"🎁",cost:Number(f.get("cost")),description:f.get("description")||""});save();close()}}
function timer(goalId){let g=S.goals.find(x=>x.id===goalId),start=Date.now(),elapsed=0,r=true,tm;modal(`<button class="close" data-a="close">×</button><h2>⏱️ ${esc(g.name)}</h2><div class="timer" id="clock">00:00:00</div><div class="actions"><button class="btn" id="pause">⏸️ Pause</button><button class="btn primary" id="finish">✓ Speichern</button></div>`);tm=setInterval(()=>{if(r)elapsed=Date.now()-start;$("#clock").textContent=new Date(elapsed).toISOString().slice(11,19)},250);$("#pause").onclick=()=>{if(r){elapsed=Date.now()-start;r=false;$("#pause").textContent="▶️ Fortsetzen"}else{start=Date.now()-elapsed;r=true;$("#pause").textContent="⏸️ Pause"}};$("#finish").onclick=()=>{clearInterval(tm);S.activities.push({id:id(),goalId,date:day(),kind:"regular",value:1,durationMinutes:Math.max(1,Math.round(elapsed/60000)),note:"Timer"});S.tokens.push({id:id(),amount:5,reason:"Timer-Aktivität"});save();close()}}
function wire(){document.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>{let a=b.dataset.a,i=b.dataset.id;if(a==="close")close();if(a==="goal-add")goalForm();if(a==="goal-edit")goalForm(S.goals.find(g=>g.id===i));if(a==="activity")activityForm(i);if(a==="timer")timer(i);if(a==="media-add")mediaForm();if(a==="media-edit")mediaForm(S.media.find(m=>m.id===i));if(a==="reward-add")rewardForm();if(a==="redeem"){let r=S.rewards.find(r=>r.id===i);if(r&&balance()>=r.cost){S.tokens.push({id:id(),amount:-r.cost,reason:"Belohnung: "+r.name});save()}}});let fs=$("#filters");if(fs)fs.onclick=e=>{let b=e.target.closest("button");if(!b)return;fs.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll("#mediaList article").forEach(c=>c.style.display=b.dataset.t==="all"||c.dataset.t===c.dataset.type?"":"none")}}
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{route=b.dataset.route;render()});
$("#fab").onclick=()=>{modal(`<button class="close" data-a="close">×</button><h2>＋ Schnell hinzufügen</h2><div class="actions"><button class="btn primary" data-a="goal-add">🎯 Ziel</button><button class="btn" data-a="media-add">📚 Sammlung</button><button class="btn" data-a="reward-add">🎁 Belohnung</button></div>`);wire()};
$("#settings").onclick=()=>modal(`<button class="close" data-a="close">×</button><h2>⚙️ Einstellungen</h2><div class="card"><h3>💾 Datensicherung</h3><p class="muted">Die Daten liegen aktuell lokal auf deinem Gerät. Export/Import wird als nächster Schritt ergänzt.</p></div><div class="card"><h3>🔔 Erinnerungen</h3><p class="muted">Die Zielstruktur ist vorbereitet. Zuverlässige Push-Erinnerungen prüfen wir separat für die PWA.</p></div><button class="btn" data-a="close">Schließen</button>`);wire();
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
render();